jobs:
  aadu_scan:
    runs-on: ubuntu-latest
    name: Scan aadu website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: aadu Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.aadrika.online/'
          rules_file_name: 'test/rules.tsv'
          cmd_options: '-a'
